exports.default = local = {
  EXEC_ENV: `'local'`,
  ORIGIN: `'http://localhost:5000'`,
  EXAM_ORIGIN: `'http://localhost:5001'`,
  API_VERSION: `'v1-dev'`,
  TIME_ZONE: `'Asia/Tokyo'`,
  TIME_LIMIT: `'5'`,
  JWT_SECRET: `'HifdFdf9uYRi3JSDZN6eRxYi5cWCBNZeSQnqAubX'`,
  DB_HOST: `'127.0.0.1'`,
  DB_PORT: `'3306'`,
  DB_NAME: `'acro_master'`,
  DB_USER: `'root'`,
  DB_PASSWORD: `''`,
  PASSPHRASE: `''`,
  MAIL_HOST_NAME: `''`,
  MAIL_USER_NAME: `''`,
  MAIL_PASSWORD: `''`,
  MAIL_PORT_NUMBER: `''`,
  MAIL_ADDRESS_FROM: `''`,
  EXAM_YEAR: `'2021'`,
  SQL_PATH: `'./src/sql/'`,
  IMPORT_TMP_PATH: `'./tmp/'`,
  LOGS_PATH: `'./logs/'`,
};
