exports.default = production = {
  EXEC_ENV: `'production'`,
  ORIGIN: `''`,
  EXAM_ORIGIN: `''`,
  API_VERSION: `''`,
  TIME_ZONE: `''`,
  TIME_LIMIT: `''`,
  JWT_SECRET: `''`,
  DB_HOST: `''`,
  DB_PORT: `''`,
  DB_NAME: `''`,
  DB_USER: `''`,
  DB_PASSWORD: `''`,
  PASSPHRASE: `''`,
  MAIL_HOST_NAME: `''`,
  MAIL_USER_NAME_GRADUATE: `''`,
  MAIL_USER_NAME_HALFWAY: `''`,
  MAIL_PORT_NUMBER: `''`,
  EXAM_YEAR: `''`,
  SQL_PATH: `''`,
  IMPORT_TMP_PATH: `''`,
  LOGS_PATH: `''`,
};
